/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-20 at 00:06:20 UTC 
 * Modify at your own risk.
 */

package com.kindhat.kindcard.service.kindcardendpoint.model;

/**
 * Model definition for KindCard.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the kindcardendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class KindCard extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("_kindCardId")
  private java.lang.String kindCardId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("_latestUserStoryDate")
  private com.google.api.client.util.DateTime latestUserStoryDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("_userStories")
  private java.util.List<UserStory> userStories;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKindCardId() {
    return kindCardId;
  }

  /**
   * @param kindCardId kindCardId or {@code null} for none
   */
  public KindCard setKindCardId(java.lang.String kindCardId) {
    this.kindCardId = kindCardId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getLatestUserStoryDate() {
    return latestUserStoryDate;
  }

  /**
   * @param latestUserStoryDate latestUserStoryDate or {@code null} for none
   */
  public KindCard setLatestUserStoryDate(com.google.api.client.util.DateTime latestUserStoryDate) {
    this.latestUserStoryDate = latestUserStoryDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<UserStory> getUserStories() {
    return userStories;
  }

  /**
   * @param userStories userStories or {@code null} for none
   */
  public KindCard setUserStories(java.util.List<UserStory> userStories) {
    this.userStories = userStories;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public KindCard setId(Key id) {
    this.id = id;
    return this;
  }

  @Override
  public KindCard set(String fieldName, Object value) {
    return (KindCard) super.set(fieldName, value);
  }

  @Override
  public KindCard clone() {
    return (KindCard) super.clone();
  }

}
